### PR TITLE
[UPD] Dotfile: .gitignore

### PR DESCRIPTION
**Pull request by kanda999**
[2920](https://www.quartile.co/web#id=2920&action=771&model=project.task&view_type=form&menu_id=505)

### CODE REVIEW

**Comment by yostashiro** [comment]
@kanda999 Can you check what happens to the adjustments to `.gitignore` when you run copier?

@AungKoKoLin1997 Do you have an insight on this?

**Comment by AungKoKoLin1997** [comment]
> @AungKoKoLin1997 Do you have an insight on this?

we don't run copier for our oca repos. We just add .pre-commit-config.yaml for setup  and .gitignore file.

**Comment by yostashiro** [comment]
@AungKoKoLin1997 Sorry I was asking about the case where we prepare dotfiles with copier.  No concerns in this particular repo.

For the record, Kanda-san has just confirmed that the adjusted content this time is also included in the copier template.

We may adjust our practice to grab .gitignore as well from the template.

**Review by yostashiro — APPROVED** [review]

**Comment by kanda999** [comment]
https://github.com/OCA/oca-addons-repo-template/blob/510592efb895bc586a22d1808d72b7125b645d86/.gitignore#L73-L74

**Pull request merged**
