### PR TITLE
[15.0][ADD] web_widget_open_tab

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**

### CODE REVIEW

**Comment by yostashiro** [comment]
@AungKoKoLin1997 Can you backport the enhancement we have made to the 16.0 version to (slightly) lower the overall customization volume?

**Review by yostashiro — APPROVED** [review]
Code review.

**Review by liuhehe1995 — COMMENTED** [review]
I performed a functional test in runboat, it worked as expected.

The module is very convenient because there is no need to deliberately open a new page to view the contents of the options.

**Review by kanda999 — APPROVED** [review]
LGTM

**Pull request merged**
